In [1]:
import numpy as np

In [4]:
a = np.array([5, 6, 9])

In [5]:
a[0]

np.int64(5)

In [8]:
a = np.array([[1,2],[3,4],[5,6]])
print("Dimension of a:", a.ndim)

Dimension of a: 2


In [9]:
a.itemsize ## size of one individual size of element

8

In [10]:
a = np.array([[1,2],[3,4],[5,6],[7,8]], dtype=np.int32)
a.itemsize

4

In [11]:
print("Shape of a:", a.shape)

Shape of a: (4, 2)


In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
l = range(0,10)
l[4]

4

In [16]:
np.arange(1,5)

array([1, 2, 3, 4])

In [17]:
np.arange(1,5,2)

array([1, 3])

In [19]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
print(a.shape)
a.reshape(2,4)

(4, 2)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [22]:
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)

In [23]:
a.ravel() ## to make one dimension / one row
### ravel doesnt effect until u store in variable

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [25]:
a.min()

np.int32(1)

In [26]:
a.max()

np.int32(8)

In [27]:
a.sum()

np.int64(36)

In [32]:
print(a)
print("Axis = 0:",a.sum(axis=0))
print("Axis = 1",a.sum(axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis = 0: [16 20]
Axis = 1 [ 3  7 11 15]
